# Site settings
title: Victoria's Profile
email: vsbravo1993@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages-24"
url: "http://vicsobravoISG.github.io"
twitter_username: n/a
github_username:  vicsobravo
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
